/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package spreadsheet.parser;

public interface ParserConstants {

  int EOF = 0;
  int EOL = 3;
  int EQUALS = 4;
  int L_BRACKET = 5;
  int R_BRACKET = 6;
  int COMMA = 7;
  int PLUS = 8;
  int MINUS = 9;
  int MULTIPLY = 10;
  int DIVIDE = 11;
  int EXP = 12;
  int LN = 13;
  int SIN = 14;
  int COS = 15;
  int TAN = 16;
  int ASIN = 17;
  int ATAN = 18;
  int ACOS = 19;
  int FLOOR = 20;
  int CEIL = 21;
  int MIN = 22;
  int MAX = 23;
  int AND = 24;
  int OR = 25;
  int LT = 26;
  int GT = 27;
  int LTE = 28;
  int GTE = 29;
  int EQ = 30;
  int NEQ = 31;
  int IF = 32;
  int NOT = 33;
  int NUM = 34;
  int FLOAT = 35;
  int INTEGER = 36;
  int DIGIT = 37;
  int POSINFINITY = 38;
  int NEGINFINITY = 39;
  int NAN = 40;
  int ID = 41;
  int COLUMN_NAME = 42;
  int ROW_NAME = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"ln\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"asin\"",
    "\"atan\"",
    "\"acos\"",
    "\"floor\"",
    "\"ceil\"",
    "\"min\"",
    "\"max\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"if\"",
    "\"!\"",
    "<NUM>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "\"Infinity\"",
    "\"-Infinity\"",
    "\"NaN\"",
    "<ID>",
    "<COLUMN_NAME>",
    "<ROW_NAME>",
  };

}
